apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
  namespace: system
type: Opaque
stringData:
  config.json: |
    {
    	"auths": {
    		"https://index.docker.io/v1/": {
    			"auth": "YWxleHRhcmdvdjpzNE0zS2UzXkgldWY="
    		}
    	}
    }
