apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.global.istio.gateway.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway  # Use Istio's ingress gateway to handle external traffic
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "{{ .Values.global.orchestrator.name }}.{{ .Values.global.ingress.domainName }}"