apiVersion: func.controller/v1alpha1
kind: Application
metadata:
  name: application-sample-3
  namespace: system
spec:
  # TODO(user): Add fields here
  sourceCode: |
    'use strict';

    const express = require('express');

    // Constants
    const PORT = 3000;
    const HOST = '0.0.0.0';

    // App
    const app = express();
    app.get('/', (req, res) => {
        res.send('Hello World');
    });

    console.log("Running on " + HOST + ":" + PORT);

    app.listen(PORT, HOST);
  nodeVersion: 15.0.0
  replicasCount: 1
