apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: system
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args: ["--dockerfile=/workspace/Dockerfile",
             "--context=dir://workspace",
             "--destination=alextargov/test-kaniko:1.0.0"]
      volumeMounts:
        - name: dockerfile-storage
          mountPath: /workspace/Dockerfile
          subPath: Dockerfile
          readOnly: true
        - name: packagejson-storage
          mountPath: /workspace/package.json
          subPath: package.json
          readOnly: true
        - name: server-storage
          mountPath: /workspace/server.js
          subPath: server.js
          readOnly: true
        - name: docker-secret
          mountPath: /kaniko/.docker/config.json
          subPath: config.json
          readOnly: true
  restartPolicy: Never
  volumes:
    - name: dockerfile-storage
      configMap:
        name: dockerfile-config
    - name: packagejson-storage
      configMap:
        name: packagejson-config
    - name: server-storage
      configMap:
        name: server-config
    - name: docker-secret
      secret:
        secretName: docker-secret
