apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: iot-system
  labels:
    app: controller
data:
  server.js: |-
    'use strict';

    const express = require('express');

    // Constants
    const PORT = 3000;
    const HOST = '0.0.0.0';

    // App
    const app = express();
    app.get('/', (req, res) => {
      res.send('Hello World');
    });

    app.listen(PORT, HOST);
    console.log(`Running on http://${HOST}:${PORT}`);